// flow-typed signature: 9a722d0541fa39664c33ffeea6b16151
// flow-typed version: <<STUB>>/execa_v^0.10.0/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'execa'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'execa' {
  declare module.exports: (
    string,
    Array<mixed>,
  ) => Promise<{
    stdout: string,
    stderr: string,
  }>;
}
